version: '3'

services:
  broker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  helper:
    build:
      context: ./helper

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

