version: '3'

services:
  broker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  consumers:
    build:
      context: ./helper
    environment:
      - PROCESSES=10
      - SCRIPT=./consumer.js
      - SLEEP_INTERVAL_MS=500

  producers:
    build:
      context: ./helper
    environment:
      - PROCESSES=10
      - SCRIPT=./producer.js
      - SLEEP_INTERVAL_MS=500

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

